package com.example.guryihii.model.network

data class RealEstateProperty(
    val advert_type: String,
    val bathrooms: String,
    val bedrooms: Int,
    val city: String,
    val country: String,
    val cover_photo: String,
    val description: String,
    val id: Int,
    val photo1: String,
    val photo2: String,
    val photo3: String,
    val photo4: String,
    val plot_area: String,
    val postal_code: String,
    val price: String,
    val profile_photo: String,
    val property_number: Int,
    val property_type: String,
    val published_status: Boolean,
    val ref_code: String,
    val slug: String,
    val street_address: String,
    val title: String,
    val total_floors: Int,
    val user: Int,
    val views: Int
)